"use client";
import {useEffect,useRef,useState} from 'react';
import {MessageCircle,Send} from 'lucide-react';
import type {ChatMessage} from '@/lib/game';
export function RoomChat({messages,you,connected,busy,onSend}:{messages:ChatMessage[];you:string;connected:boolean;busy:boolean;onSend:(text:string,id:string)=>Promise<void>}){
 const[draft,setDraft]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState('');
 const log=useRef<HTMLDivElement>(null),follow=useRef(true),locked=useRef(false),retry=useRef<{text:string;id:string}|null>(null);
 const lastId=messages.at(-1)?.id;
 useEffect(()=>{if(follow.current&&log.current)log.current.scrollTop=log.current.scrollHeight},[lastId]);
 async function submit(){const text=draft.trim();if(!text||text.length>300||locked.current||busy||!connected)return;locked.current=true;setSending(true);setError('');if(retry.current?.text!==text)retry.current={text,id:crypto.randomUUID()};try{await onSend(text,retry.current!.id);setDraft('');retry.current=null;follow.current=true;if(log.current)log.current.scrollTop=log.current.scrollHeight}catch(e){setError(e instanceof Error?e.message:'訊息未送出')}finally{locked.current=false;setSending(false)}}
 return <section className="room-chat" aria-label="房間聊天"><div className="chat-heading"><h3><MessageCircle size={18}/> 房間聊天</h3><span>{connected?'同房玩家可見':'重新連線中'}</span></div><div ref={log} className="chat-log" role="log" aria-label="聊天訊息" aria-live="polite" aria-relevant="additions" onScroll={()=>{const el=log.current;if(el)follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<45}}>{messages.length?messages.map(m=><article className={'chat-message '+(m.playerId===you?'mine':'')} key={m.id}><div className="avatar" aria-hidden="true"><div className="cat" style={{backgroundPosition:`${m.avatar%6*20}% ${Math.floor(m.avatar/6)*20}%`}}/></div><div className="chat-content"><div className="chat-meta"><strong>{m.name}{m.playerId===you?' · 你':''}</strong><time dateTime={new Date(m.sentAt).toISOString()}>{new Date(m.sentAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',hour12:false})}</time></div><p>{m.text}</p></div></article>):<p className="chat-empty">跟大家打個招呼吧！<br/>等待開局時也能聊天。</p>}</div><form onSubmit={e=>{e.preventDefault();void submit()}} className="chat-form"><label htmlFor="chat-message" className="sr-only">聊天訊息</label><textarea id="chat-message" rows={2} maxLength={300} placeholder="傳個訊息…" value={draft} disabled={sending} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.nativeEvent.keyCode!==229){e.preventDefault();void submit()}}}/><div className="chat-actions"><span>{draft.length} / 300</span><button type="submit" disabled={!draft.trim()||sending||busy||!connected}><Send size={15}/>{sending?'傳送中':'傳送'}</button></div>{error?<p className="error" role="alert">{error}</p>:null}</form><p className="chat-note">保留最近 100 則 · Enter 傳送，Shift＋Enter 換行</p></section>
}
