'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,MicOff,Radio} from 'lucide-react';

type VoiceMember={id:string;name:string;avatar:number};
type VoiceSignal={id:string;senderId:string;kind:'offer'|'answer';payload:string;createdAt:number};
type PeerAudio={source:MediaStreamAudioSourceNode;analyser:AnalyserNode;data:Uint8Array<ArrayBuffer>};
const ICE_SERVERS:RTCIceServer[]=[{urls:'stun:stun.cloudflare.com:3478'}];

export function VoiceChat({roomCode,playerId,token,disabled,onState}:{roomCode:string;playerId:string;token:string;disabled:boolean;onState:(state:{members:string[];speaking:string[]})=>void}){
 const[joined,setJoined]=useState(false),[muted,setMuted]=useState(false),[count,setCount]=useState(0),[error,setError]=useState(''),[connecting,setConnecting]=useState(false);
 const joinedRef=useRef(false),streamRef=useRef<MediaStream|null>(null),peers=useRef(new Map<string,RTCPeerConnection>()),processed=useRef(new Set<string>()),timer=useRef<ReturnType<typeof setTimeout>|null>(null),audio=useRef<AudioContext|null>(null),analysers=useRef(new Map<string,PeerAudio>()),meter=useRef<ReturnType<typeof setInterval>|null>(null),membersRef=useRef<string[]>([]);
 const auth={'Content-Type':'application/json',Authorization:'Bearer '+token};
 function announce(speaking:string[]=[]){onState({members:membersRef.current,speaking})}
 async function post(body:Record<string,unknown>){const response=await fetch('/api/voice',{method:'POST',headers:auth,body:JSON.stringify({code:roomCode,...body})});const data=await response.json() as {error?:string};if(!response.ok)throw Error(data.error||'語音連線失敗');return data}
 function closePeer(id:string){peers.current.get(id)?.close();peers.current.delete(id);analysers.current.delete(id)}
 function watchAudio(id:string,media:MediaStream,local=false){const context=audio.current;if(!context)return;const source=context.createMediaStreamSource(media),analyser=context.createAnalyser();analyser.fftSize=256;source.connect(analyser);if(!local)analyser.connect(context.destination);analysers.current.set(id,{source,analyser,data:new Uint8Array(analyser.fftSize)})}
 function startMeter(){if(meter.current)clearInterval(meter.current);meter.current=setInterval(()=>{const speaking:string[]=[];analysers.current.forEach((entry,id)=>{entry.analyser.getByteTimeDomainData(entry.data);let energy=0;for(const value of entry.data){const sample=(value-128)/128;energy+=sample*sample}if(Math.sqrt(energy/entry.data.length)>.035)speaking.push(id)});announce(speaking)},220)}
 async function waitForIce(pc:RTCPeerConnection){if(pc.iceGatheringState==='complete')return;await new Promise<void>(resolve=>{const finish=()=>{pc.removeEventListener('icegatheringstatechange',change);resolve()},change=()=>{if(pc.iceGatheringState==='complete')finish()};pc.addEventListener('icegatheringstatechange',change);setTimeout(finish,4500)})}
 async function signal(targetId:string,kind:'offer'|'answer',payload:string){await post({action:'signal',signalId:crypto.randomUUID(),targetId,kind,payload})}
 function makePeer(id:string){const existing=peers.current.get(id);if(existing)return existing;const pc=new RTCPeerConnection({iceServers:ICE_SERVERS});peers.current.set(id,pc);streamRef.current?.getTracks().forEach(track=>pc.addTrack(track,streamRef.current!));pc.ontrack=event=>{const media=event.streams[0]??new MediaStream([event.track]);if(!analysers.current.has(id))watchAudio(id,media)};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState))closePeer(id)};return pc}
 async function offer(id:string){const pc=makePeer(id);if(pc.signalingState!=='stable'||pc.localDescription)return;await pc.setLocalDescription(await pc.createOffer());await waitForIce(pc);if(pc.localDescription?.sdp)await signal(id,'offer',pc.localDescription.sdp)}
 async function receive(message:VoiceSignal){if(processed.current.has(message.id))return;processed.current.add(message.id);const pc=makePeer(message.senderId);if(message.kind==='offer'){await pc.setRemoteDescription({type:'offer',sdp:message.payload});await pc.setLocalDescription(await pc.createAnswer());await waitForIce(pc);if(pc.localDescription?.sdp)await signal(message.senderId,'answer',pc.localDescription.sdp)}else if(pc.signalingState==='have-local-offer')await pc.setRemoteDescription({type:'answer',sdp:message.payload})}
 async function poll(){if(!joinedRef.current)return;try{const response=await fetch('/api/voice?code='+roomCode,{headers:{Authorization:'Bearer '+token},cache:'no-store'}),data=await response.json() as {members?:VoiceMember[];signals?:VoiceSignal[];error?:string};if(!response.ok)throw Error(data.error||'語音連線失敗');const ids=(data.members??[]).map(item=>item.id);membersRef.current=ids;setCount(ids.length);announce();for(const id of [...peers.current.keys()])if(!ids.includes(id))closePeer(id);for(const message of data.signals??[])await receive(message);for(const id of ids)if(id!==playerId&&!peers.current.has(id)&&playerId<id)await offer(id);setError('')}catch(reason){setError(reason instanceof Error?reason.message:'語音正在重新連線')}finally{if(joinedRef.current)timer.current=setTimeout(poll,900)}}
 async function join(){if(disabled||connecting)return;setConnecting(true);setError('');try{if(!navigator.mediaDevices?.getUserMedia||typeof RTCPeerConnection==='undefined')throw Error('這個瀏覽器不支援語音聊天');const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});streamRef.current=stream;const AudioCtor=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtor)throw Error('這個瀏覽器不支援語音播放');audio.current=new AudioCtor();await audio.current.resume();watchAudio(playerId,stream,true);await post({action:'join'});joinedRef.current=true;setJoined(true);setMuted(false);membersRef.current=[playerId];setCount(1);announce();startMeter();void poll()}catch(reason){streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;analysers.current.clear();void audio.current?.close();audio.current=null;setError(reason instanceof DOMException&&reason.name==='NotAllowedError'?'請允許麥克風權限後再試一次':reason instanceof Error?reason.message:'無法開啟麥克風')}finally{setConnecting(false)}}
 function toggle(){const next=!muted;streamRef.current?.getAudioTracks().forEach(track=>{track.enabled=!next});setMuted(next)}
 function leave(){joinedRef.current=false;if(timer.current)clearTimeout(timer.current);if(meter.current)clearInterval(meter.current);peers.current.forEach(peer=>peer.close());peers.current.clear();analysers.current.clear();streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;void audio.current?.close();audio.current=null;membersRef.current=[];announce();setJoined(false);setMuted(false);setCount(0);void post({action:'leave'}).catch(()=>{})}
 useEffect(()=>leave,[roomCode,playerId]);
 return <div className={'voice-chat '+(joined?'joined ':'')+(muted?'muted':'')}>
  <button type="button" className="voice-main" disabled={disabled||connecting} aria-pressed={joined&&!muted} title={joined?(muted?'重新開啟麥克風':'將麥克風靜音'):'加入房間語音'} onClick={()=>joined?toggle():void join()}>{connecting?<Radio className="voice-connecting" size={16}/>:joined&&!muted?<Mic size={16}/>:<MicOff size={16}/>}<span>{connecting?'連線中':joined?(muted?'已靜音':'麥克風開'):'語音聊天'}</span>{joined?<small>{count}</small>:null}</button>
  {joined?<button type="button" className="voice-leave" onClick={leave}>離開</button>:null}
  {error?<span className="voice-error" role="alert">{error}</span>:null}
 </div>
}
